# Generated by Django 4.1.2 on 2022-10-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
