# Generated by Django 4.1.2 on 2022-10-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
